### PR TITLE
[RandomNoa] Version 2

### PR DESCRIPTION
**Pull request by reonanyubara**
## Type

- [x] Bug Fix
- [x] Enhancement
- [x] New Feature
- [ ] Other

## Description of the changes
This PR includes everything for RandomNoa v2. Refer #80 for more information.

## Have you tested your changes?
No, WIP.

### CODE REVIEW

**Review by JeffJrShim — COMMENTED** [review]
For now, everything seems fine. However, I will not give full approval yet, as we have a lot more to work on.

**Comment by Chii-Onan** [comment]
I believe we should utilize dataclasses when returning the data

**Review by Kuro-Rui — APPROVED** [review]

**Review by Chii-Onan — APPROVED** [review]
Hi, these changes look great to me!

Just 1 question for @JeffJrShim , do you want these changes merged before the D.py V2 release or after it?

**Comment by JeffJrShim** [comment]
> Hi, these changes look great to me!
> 
> Just 1 question for @JeffJrShim , do you want these changes merged before the D.py V2 release or after it?

I'll be merging now. A dpy release should come again later 😂

**Pull request merged**
