### PR TITLE
[RandomNoa] Credits for bae.lena.moe (New host!)

### PR DESCRIPTION
**Pull request by DJTOMATO**
Footer stuff

## Type

- [ X ] Bug Fix
- [ ] Enhancement
- [ ] New Feature
- [ ] Other

## Description of the changes
||Ogey||
## Have you tested your changes?
||rrat||

### CODE REVIEW

**Review by JeffJrShim — APPROVED** [review]
looks good! (for now)

**Review by JeffJrShim — CHANGES_REQUESTED** [review]
blaaaaaack

**Comment by DJTOMATO** [comment]
black

**Review by JeffJrShim — APPROVED** [review]
lgtm now! thankiu

**Pull request merged**
