### PR TITLE
[Repo] DPY2/Red3.5 Changes PR

### LINKED ISSUE #52: d.py 2.0/ Red 3.5 changes.
This issue will currently show my cogs that are supported for DPY 2. More information to come later.

### PR DESCRIPTION
**Pull request by JeffJrShim**
## Type

- [x] Bug Fix
- [x] Enhancement
- [ ] New Feature
- [ ] Other

## Description of the changes
This PR will include all of the changes made for DPY2/Red 3.5. 
Closes #52. 

Currently, all cogs *will* load without issue, but we will need to wait until Red 3.5 is released to address and fix the given changes.
## Have you tested your changes?
Yes

### CODE REVIEW

**Comment by JeffJrShim** [comment]
## Have you tested your changes?
Yes

**Comment by guacaplushy** [comment]
Lgtm afaik, looks pretty simple. Sure you got it all?

**Comment by JeffJrShim** [comment]
Not yet. I still have a cog to port.

**Comment by JeffJrShim** [comment]
Please read [this](https://github.com/Noa-DiscordBot/noa-cogs/issues/52#issuecomment-1110872240) comment, for more information regarding this PR.

**Review by Chii-Onan — CHANGES_REQUESTED** [review]
These changes look alright to me!

But before we decide to make this a proper PR, I'd like to request that we use bundled data paths instead of fetching the install path from the cog manager as suggested by Jack.

For this change the following cogs will be affected:

- BreadFact
- RandomNoa

**Comment by Chii-Onan** [comment]
Can we merge this changes on a branch called Dpy2 to make it available for other people who run dev version of red?

**Pull request merged**
